-- Run this in Supabase SQL Editor to set up your database
-- This creates one table that stores every completed set for both users

create table if not exists completions (
  id bigint generated by default as identity primary key,
  user_name text not null,           -- 'will' or 'gf'
  week_start date not null,           -- Monday of the week, e.g. '2026-05-18'
  day_id text not null,               -- 'mon', 'tue', etc.
  exercise_id text not null,          -- 'pushups', 'squats', etc.
  set_index integer not null,         -- 0, 1, 2 (which set within the exercise)
  completed_at timestamptz default now(),
  unique (user_name, week_start, day_id, exercise_id, set_index)
);

-- Enable Row Level Security but allow anyone to read/write
-- (since this is a private 2-person app with no login)
alter table completions enable row level security;

create policy "Anyone can read completions"
  on completions for select
  using (true);

create policy "Anyone can insert completions"
  on completions for insert
  with check (true);

create policy "Anyone can delete completions"
  on completions for delete
  using (true);

-- Enable realtime so progress syncs live between devices
alter publication supabase_realtime add table completions;
